services:
  db:
    image: postgres:15
    container_name: iot_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"

  service:
    build: .
    container_name: telemetry_service
    restart: always
    depends_on:
      - db
      - mqtt

volumes:
  pgdata: